### ISSUE TITLE
Research what functions we want for the HexTool

### ISSUE THREAD

**Issue by ConnorScrums** [ConnorScrums/HexTool#4]
These will be stories for the team
Unit testing
Code reviews

**Comment by ConnorScrums** [comment]
Vincent too

**Comment by AnthonyGoncharenko** [comment]
I wrote some code to set up a basic hashing function choice logic + first hashing function located on (hex-tool-backend-functionality-part-1) branch

**Comment by ConnorScrums** [comment]
Reviewed branch. Want to add some functions too - working on folding and mid-square.

**Comment by ConnorScrums** [comment]
We have understanding of what hashers we can add to the tool. Potential discussion for other function(other than hashing)
